version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4 
      - OLLAMA_MAX_LOADED_MODELS=2
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models:
