version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull llama3 &&
      tail -f /dev/null
      "
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  ollama_models:
